// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Project struct {
	ID          int64
	Name        string
	Description sql.NullString
	Deadline    time.Time
}

type ProjectTask struct {
	ID          int64
	ProjectID   int64
	Name        string
	Description sql.NullString
	Size        int64
	Challenge   int64
}

type Quotum struct {
	ID                 int64
	FixedTime          int64
	Duration           int64
	RecurrenceInterval int64
}

type Task struct {
	ID          int64
	Name        string
	Description sql.NullString
	Deadline    time.Time
	Size        int64
	Challenge   int64
}
